.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH coreos-installer 8  "coreos-installer 0.25.0" 
.SH NAME
coreos\-installer\-iso\-kargs\-modify \- Modify kernel args in an ISO image
.SH SYNOPSIS
\fBcoreos\-installer\-iso\-kargs\-modify\fR [\fB\-a\fR|\fB\-\-append\fR] [\fB\-d\fR|\fB\-\-delete\fR] [\fB\-r\fR|\fB\-\-replace\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIISO\fR> 
.SH DESCRIPTION
Modify kernel args in an ISO image
.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-append\fR \fI<KARG>\fR
Kernel argument to append
.TP
\fB\-d\fR, \fB\-\-delete\fR \fI<KARG>\fR
Kernel argument to delete
.TP
\fB\-r\fR, \fB\-\-replace\fR \fI<KARG=OLDVAL=NEWVAL>\fR
Kernel argument to replace
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<PATH>\fR
Write ISO to a new output file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
<\fIISO\fR>
ISO image
.SH VERSION
v0.25.0
