.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH coreos-installer 8  "coreos-installer 0.13.1" 
.SH NAME
coreos\-installer\-pxe \- Commands to manage a CoreOS live PXE image
.SH SYNOPSIS
\fBcoreos\-installer\-pxe\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands to manage a CoreOS live PXE image
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.SH SUBCOMMANDS
.TP
coreos\-installer\-pxe\-customize(8)
Create a custom live PXE boot config
.TP
coreos\-installer\-pxe\-ignition(8)
Commands to manage a live PXE Ignition config
.TP
coreos\-installer\-pxe\-network(8)
Commands to manage live PXE network settings
.TP
coreos\-installer\-pxe\-help(8)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.13.1
