.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH coreos-installer 8  "coreos-installer 0.25.0" 
.SH NAME
coreos\-installer\-iso\-ignition\-remove \- Remove an existing embedded Ignition config from an ISO image
.SH SYNOPSIS
\fBcoreos\-installer\-iso\-ignition\-remove\fR [\fB\-o\fR|\fB\-\-output\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIISO\fR> 
.SH DESCRIPTION
Remove an existing embedded Ignition config from an ISO image
.SH OPTIONS
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<path>\fR
Write ISO to a new output file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
<\fIISO\fR>
ISO image
.SH VERSION
v0.25.0
