.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH coreos-installer 8  "coreos-installer 0.25.0" 
.SH NAME
coreos\-installer\-list\-stream \- List available images in a Fedora CoreOS stream
.SH SYNOPSIS
\fBcoreos\-installer\-list\-stream\fR [\fB\-s\fR|\fB\-\-stream\fR] [\fB\-\-stream\-base\-url\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
List available images in a Fedora CoreOS stream
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-stream\fR \fI<name>\fR [default: stable]
Fedora CoreOS stream
.TP
\fB\-\-stream\-base\-url\fR \fI<URL>\fR
Base URL for Fedora CoreOS stream metadata
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.25.0
