.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH coreos-installer 8  "coreos-installer 0.13.1" 
.SH NAME
coreos\-installer\-iso\-ignition\-show \- Show the embedded Ignition config from an ISO image
.SH SYNOPSIS
\fBcoreos\-installer\-iso\-ignition\-show\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIISO\fR> 
.SH DESCRIPTION
Show the embedded Ignition config from an ISO image
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.TP
<\fIISO\fR>
ISO image
.SH VERSION
v0.13.1
