.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH coreos-installer 8  "coreos-installer 0.13.1" 
.SH NAME
coreos\-installer\-iso\-network\-embed \- Embed network settings in an ISO image
.SH SYNOPSIS
\fBcoreos\-installer\-iso\-network\-embed\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fB\-k\fR|\fB\-\-keyfile\fR> [\fB\-f\fR|\fB\-\-force\fR] [\fB\-o\fR|\fB\-\-output\fR] <\fIISO\fR> 
.SH DESCRIPTION
Embed network settings in an ISO image
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.TP
\fB\-k\fR, \fB\-\-keyfile\fR=\fIpath\fR
NetworkManager keyfile to embed
.TP
\fB\-f\fR, \fB\-\-force\fR
Overwrite existing network settings
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIpath\fR
Write ISO to a new output file
.TP
<\fIISO\fR>
ISO image
.SH VERSION
v0.13.1
