.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH coreos-installer 8  "coreos-installer 0.25.0" 
.SH NAME
coreos\-installer\-download \- Download a CoreOS image
.SH SYNOPSIS
\fBcoreos\-installer\-download\fR [\fB\-s\fR|\fB\-\-stream\fR] [\fB\-a\fR|\fB\-\-architecture\fR] [\fB\-p\fR|\fB\-\-platform\fR] [\fB\-f\fR|\fB\-\-format\fR] [\fB\-u\fR|\fB\-\-image\-url\fR] [\fB\-C\fR|\fB\-\-directory\fR] [\fB\-d\fR|\fB\-\-decompress\fR] [\fB\-\-insecure\fR] [\fB\-\-stream\-base\-url\fR] [\fB\-\-fetch\-retries\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Download a CoreOS image
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-stream\fR \fI<name>\fR [default: stable]
Fedora CoreOS stream
.TP
\fB\-a\fR, \fB\-\-architecture\fR \fI<name>\fR [default: x86_64]
Target CPU architecture
.TP
\fB\-p\fR, \fB\-\-platform\fR \fI<name>\fR [default: metal]
Fedora CoreOS platform name
.TP
\fB\-f\fR, \fB\-\-format\fR \fI<name>\fR [default: raw.xz]
Image format
.TP
\fB\-u\fR, \fB\-\-image\-url\fR \fI<URL>\fR
Manually specify the image URL
.TP
\fB\-C\fR, \fB\-\-directory\fR \fI<path>\fR [default: .]
Destination directory
.TP
\fB\-d\fR, \fB\-\-decompress\fR
Decompress image and don\*(Aqt save signature
.TP
\fB\-\-insecure\fR
Allow unsigned image
.TP
\fB\-\-stream\-base\-url\fR \fI<URL>\fR
Base URL for Fedora CoreOS stream metadata
.TP
\fB\-\-fetch\-retries\fR \fI<N>\fR [default: 0]
Fetch retries, or "infinite"
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.25.0
