.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH coreos-installer 8  "coreos-installer 0.13.1" 
.SH NAME
coreos\-installer\-pxe\-ignition\-wrap \- Wrap an Ignition config in an initrd image
.SH SYNOPSIS
\fBcoreos\-installer\-pxe\-ignition\-wrap\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fB\-i\fR|\fB\-\-ignition\-file\fR] [\fB\-o\fR|\fB\-\-output\fR] 
.SH DESCRIPTION
Wrap an Ignition config in an initrd image
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.TP
\fB\-i\fR, \fB\-\-ignition\-file\fR=\fIpath\fR
Ignition config to wrap [default: stdin]
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIpath\fR
Write to a file instead of stdout
.SH VERSION
v0.13.1
