.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH coreos-installer 8  "coreos-installer 0.13.1" 
.SH NAME
coreos\-installer\-iso\-network\-extract \- Extract embedded network settings from an ISO image
.SH SYNOPSIS
\fBcoreos\-installer\-iso\-network\-extract\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fB\-C\fR|\fB\-\-directory\fR] <\fIISO\fR> 
.SH DESCRIPTION
Extract embedded network settings from an ISO image
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.TP
\fB\-C\fR, \fB\-\-directory\fR=\fIpath\fR
Extract to directory instead of stdout
.TP
<\fIISO\fR>
ISO image
.SH VERSION
v0.13.1
