.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH coreos-installer 8  "coreos-installer 0.25.0" 
.SH NAME
coreos\-installer\-pxe\-network\-unwrap \- Extract wrapped network settings from an initrd image
.SH SYNOPSIS
\fBcoreos\-installer\-pxe\-network\-unwrap\fR [\fB\-C\fR|\fB\-\-directory\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIinitrd\fR] 
.SH DESCRIPTION
Extract wrapped network settings from an initrd image
.SH OPTIONS
.TP
\fB\-C\fR, \fB\-\-directory\fR \fI<path>\fR
Extract to directory instead of stdout
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fIinitrd\fR]
initrd image [default: stdin]
.SH VERSION
v0.25.0
