#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

set -e

UNIT_DIR="${1:-/tmp}"

cmdline=( $(</proc/cmdline) )
karg() {
    local name="$1" value="$2"
    for arg in "${cmdline[@]}"; do
        if [[ "${arg%%=*}" == "${name}" ]]; then
            value="${arg#*=}"
        fi
    done
    echo "${value}"
}

karg_bool() {
    local value=$(karg "$@")
    case "$value" in
        ""|0|no|off) return 1;;
        *) return 0;;
    esac
}

if [ -n "$(karg coreos.inst.install_dev)" ]; then
    ln -sf "/usr/lib/systemd/system/coreos-installer.target" \
        "${UNIT_DIR}/default.target"

    # Create precondition for coreos-installer-reboot.service if requested
    if ! karg_bool coreos.inst.skip_reboot; then
        touch /run/coreos-installer-reboot
    fi

    # Allow emergency.service to execute even with locked root account
    mkdir -p /etc/systemd/system/emergency.service.d
    echo -e '[Service]\nEnvironment=SYSTEMD_SULOGIN_FORCE=1\n' \
        > /etc/systemd/system/emergency.service.d/override.conf
fi
